- README.md
Please include a summary of the change and which issue is fixed. Also, please include the motivation and context for the change. List any dependencies that are required for this change.
> docs: remove ge ref

- README.md
- examples/default/outputs.tf
- examples/existing-resources/outputs.tf
- main.tf
- module-metadata.json
- outputs.tf
Add name output from key protect instance to output of the all inclusive module
> feat: add instance name output

- tests/other_test.go
Please include a summary of the change and which issue is fixed. Also, please include the motivation and context for the change. List any dependencies that are required for this change.
> test: fix other test

- .github/workflows/publish.yml
- module.yaml
- tests/pr_test.go
This is the first part of publishing to Techzone. After the module is onboarded we can add the notify step which triggers the catalog update.
> Publish techzone

- README.md
Triggering a new release and removing scaffolding reference since there is no public scaffolding
> fix: remove scaffolding ref

- README.md
Matches module names with the ones specified in [PR 28](https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-key/pull/28) and [PR 26](https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-key-ring/pull/26)
> docs: update title and description

- .github/workflows/verify.yaml
> ci: add verify workflow

- README.md
- examples/slz/README.md
- examples/slz/main.tf
- examples/slz/outputs.tf
- examples/slz/providers.tf
- examples/slz/variables.tf
- examples/slz/version.tf
- tests/other_test.go
Adds an example with the default variables used in SLZ, resolves https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-all-inclusive/issues/196
Added a new example with defaults specific to SLZ
---
- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.
The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
> chore: add example with SLZ defaults

- .github/settings.yml
- README.md
Renaming module from `terraform-ibm-key-protect-all-inclusive` to `terraform-ibm-kms-all-inclusive`
```
/run pipeline
```
> feat: change module name from key-protect to kms

- .secrets.baseline
- README.md
- tests/go.mod
Update documentation to reflect our ability to create keys in both key protect and hpcs instances.
Also update some broken badging from name change
```
/run pipeline
```
> docs: update documentation to reflect kms key capability

- ibm_catalog.json
- solutions/standard/version.tf
solution should comply with the following rules from "CIS IBM Cloud Foundations Benchmark" profile:
```
/run pipeline
```
> Update DA to claim from "CIS IBM Cloud Foundations Benchmark" profile

- .secrets.baseline
- README.md
- examples/basic/version.tf
- examples/existing-resources/version.tf
- main.tf
- solutions/standard/README.md
- solutions/standard/variables.tf
- tests/pr_test.go
- version.tf
update module to required `>= 1.64.0` ibm provider to pull in the fix for https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5154
```
/run pipeline
```
> fix(deps): update module to required `>= 1.64.0` ibm provider

- ibm_catalog.json
- solutions/standard/catalogValidationValues.json.template
- solutions/standard/main.tf
- solutions/standard/variables.tf
- tests/pr_test.go
Issue: https://github.com/terraform-ibm-modules/terraform-ibm-kms-all-inclusive/issues/447
```
/run pipeline
```
> feat: update DA inputs SKIP UPGRADE TEST

- ibm_catalog.json
issue: https://github.com/terraform-ibm-modules/terraform-ibm-kms-all-inclusive/issues/442
```
/run pipeline
```
> feat: add inputs to ibm_catalog.json

- solutions/standard/main.tf
- solutions/standard/variables.tf
https://github.com/terraform-ibm-modules/terraform-ibm-kms-all-inclusive/issues/478
```
/run pipeline
```
> fix: expose rotation_interval_month

- solutions/standard/version.tf
> chore: bump provider version

- solutions/standard/outputs.tf
Added existing_kms_instance_crn output in DA.
[Git Issue](https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/issues/33)
```
/run pipeline
```
> refactor: added existing_kms_instance_crn output in DA

- examples/advanced/main.tf
Update KMS all inclusive which removes key ring force delete because it is deprecated by the provider
```
/run pipeline
```
> fix(deps): code change should have been done with KMS bump

- README.md
- examples/advanced/main.tf
- examples/advanced/version.tf
- examples/basic/version.tf
- examples/existing-resources/version.tf
- main.tf
- version.tf
Update terraform terraform-ibm-modules/cbr/ibm to v1.28.1 
Update required provider version to >= 1.70.0 to pick up the fix for this provider issue: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5590
Update terraform terraform-ibm-modules/cbr/ibm to v1.28.1 
Update required provider version to >= 1.70.0 to pick up the fix for this provider issue: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5590
```
/run pipeline
```
- Use a conventional commit message to set the release level. Follow the …
> fix(deps): update terraform terraform-ibm-modules/cbr/ibm to v1.28.1

- README.md
- examples/advanced/outputs.tf
- examples/basic/outputs.tf
- examples/existing-resources/outputs.tf
- main.tf
- outputs.tf
- solutions/standard/outputs.tf
add new output `kms_account_id`
```
/run pipeline
```
> feat: add new output `kms_account_id`

- README.md
- examples/advanced/version.tf
- examples/basic/version.tf
- examples/existing-resources/version.tf
- main.tf
- solutions/standard/version.tf
- variables.tf
- version.tf
refactor: variable cross object referencing
```
/run pipeline
```
> refactor: variable cross object referencing

- .catalog-onboard-pipeline.yaml
- ibm_catalog.json
- solutions/fully-configurable/variables.tf
- solutions/security-enforced/variables.tf
> fix: remove invalid variation

- ibm_catalog.json
> fix: add architecture description

- ibm_catalog.json
> fix: update account config version

- ibm_catalog.json
> add support for ca-mon

- .secrets.baseline
- examples/advanced/README.md
- examples/advanced/main.tf
- ibm_catalog.json
- tests/other_test.go
- tests/pr_test.go
- update account config DA to latest
- test and example cleanup
```
/run pipeline
```
> fix(deps): update DA dependencies  + example / tests cleanup
